### ISSUE TITLE
App crashes when trying to call/video call

### ISSUE THREAD

**Issue by tsuby** [Aluxian/Facebook-Messenger-Desktop#84] opened 2015-05-11 18:23 UTC
On Windows 8.1. 
Great app, btw! Congrats!
Tine sus munca buna.

**Comment by mrbumpy409** [comment] 2015-05-13 02:56
This happens for me as well on Kubuntu 14.04 64-bit. Running Messenger for Desktop from the command line provides no useful output from the crash.

**Comment by tnga** [comment] 2015-05-13 22:23
Event on my UMI (Ubuntu 14.04 32-bit).

**Comment by Aluxian** [comment] 2015-05-31 10:18
Duplicate of #24

**Closed by Aluxian** 2015-05-31 10:18 UTC
