### ISSUE TITLE
System tray icon for Linux desktops

### ISSUE THREAD

**Issue by TheBlackViper1996** [Aluxian/Facebook-Messenger-Desktop#196] opened 2015-07-25 00:24 UTC
I find it rather annoying that I cannot run this app in the background and have it as a system tray icon like I can with Pidgin and Telegram. you have this in the Windows version so please add it to the Linux version.
It would also be nice if there was an option to start it minimised and have it run on start-up automatically, I can always add it to the autostart folder myself but that isn't as convenient.

all you need to do to make it autorun in Linux is add a .desktop file to /home/(username)/.config/autostart, e.g. /home/matty/.config/autostart

The contents of the .desktop file should look something like this

[Desktop Entry]
Type=Application
Version=1.0
GenericName=Messenger
Name=Facebook Messenger
Comment=Messenger for Desktop
Exec=/opt/MessengerForDesktop/Messenger
Icon=messengerfordesktop
Terminal=false
Categories=Network;Chat;
StartupNotify=false #notify the user the application has started with a flashing or pulsing icon
X-GNOME-Autostart-Delay=60 #How long to wait in seconds after logging in before starting

**Comment by devilirium** [comment] 2015-07-25 07:57
While this issue must be resolved, you'll have to wait for about a month before real development will start. Aluxian is not available for the next 2 weeks. Also he is working on a new base, which I guess will more advanced.

**Comment by atroxix** [comment] 2015-11-23 08:39
I see this was introduced in 1.4.1, but disabled again in 1.4.3. Why was that? Are there any plans to bring it back?

**Comment by cassiodoroVicinetti** [comment] 2015-12-30 20:35
@atroxix https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/165#issuecomment-116745098

**Comment by DoctorJellyface** [comment] 2016-01-18 16:21
Those comments are half a year ago.

**Comment by Sytten** [comment] 2016-06-28 03:31
The issue is resolved in the new beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Closed by Sytten** 2016-06-28 03:31 UTC
