### ISSUE TITLE
More than one instance!

### ISSUE THREAD

**Issue by MDTomate** [Aluxian/Facebook-Messenger-Desktop#316] opened 2016-01-07 21:12 UTC
I have the fixed application on the taskbar. When I close the application, minimizing it to the tray, and click on the application icon in the Start Menu or the taskbar, instead of picking up the application open in the tray, it creates a new instance of the application, duplicating it. Some certainty of how to solve this?
![Four instances!](https://cloud.githubusercontent.com/assets/16599856/12182926/8b8c0e5c-b572-11e5-8248-007ebb7b0678.png)

**Comment by SnoringFrog** [comment] 2016-01-25 18:28
This is a duplicate of issue #311

**Comment by Sytten** [comment] 2016-06-26 22:00
Resolved, please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Closed by Sytten** 2016-06-26 22:00 UTC
