### ISSUE TITLE
can't start application

### ISSUE THREAD

**Issue by shenglong209** [Aluxian/Facebook-Messenger-Desktop#374] opened 2016-03-17 17:05 UTC
Hi, 
i try to build this application in my ubuntu 15.10, after install it's on my ubuntu, i can't start applicattion and  get an error:

"[25577:0318/000147:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on."

Please help  me know how to fix it, thank you so much.

i try build manualy because in your release, when change to dark theme, text-color is look like box background and its hard to look.

**Comment by ViBENo1** [comment] 2016-03-17 23:52
same here but the error message continues with the following
`ATTENTION: default value of option force_s3tc_enable overridden by environment.
[3681:0318/004444:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR`

and the application usually can't load the content.
OS: Ubuntu 14.04, 64 bit

**Comment by Sytten** [comment] 2016-03-19 04:31
Try my fork, I've already done all the work ;)
SUID sandbox should not be an issue, thats strange...
Please confirm if it works or not...

**Comment by shenglong209** [comment] 2016-03-19 04:55
it freez with this message when i try to run "npm install"
`engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.25","npm":"1.4.21"})`

**Comment by Sytten** [comment] 2016-03-19 05:10
You have a version of node already installed probably in global that is outdated, its only thing I can see since I dont have any trouble what so ever when I run npm install...

**Comment by shenglong209** [comment] 2016-03-19 05:27
:( 
the binaries was installed 
dark theme is very ugly
 http://i.imgur.com/hfxBOkA.png

**Comment by jackwilsdon** [comment] 2016-03-19 09:13
@shenglong209, there is already some issue open for the theming issue: #368, #349, #152.

**Comment by shenglong209** [comment] 2016-03-19 09:27
ok, thank you @jackwilsdon , i updating my node, i will fix it manual ^^

**Comment by Sytten** [comment] 2016-03-19 20:36
Or you can use my fork lol

**Comment by ViBENo1** [comment] 2016-03-20 02:20
@Sytten your version drains the CPU and basically stuck my system

**Comment by Sytten** [comment] 2016-03-20 22:49
Thats strange. If you are on ubuntu, thats because of the system tray from what I heard.

**Comment by ViBENo1** [comment] 2016-03-20 22:50
yes, i'm on Ubuntu 14.04 64 bit.

**Comment by Sytten** [comment] 2016-03-20 22:53
Check this out: https://github.com/Sytten/Facebook-Messenger-Desktop/issues/14
Tell me if it works...

**Comment by ViBENo1** [comment] 2016-03-21 02:47
i guess yes but that does not worth the cost for me to use a single application.
i cleared the cache and reinstalled. now i have this SUID error message too in console. it still eats my CPU and i cannot login. it's loading forever. then when i tried to close it i got the following error message:

`[7551:0321/033317:WARNING:x11_util.cc(1490)] X error received: serial 7634, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)`

and i don't understand one thing. the original version on Windows works fine. why?

**Comment by Sytten** [comment] 2016-03-21 04:37
Well I cant really help you if you don't want to use a system tray. 
The problem, I suspect, is that the app tries to register to the Ubuntu tray which refuses and it keeps trying forever (that would explain the high CPU load). When I tried on Ubuntu (latest), it worked fine with the app I suggested. Anyway, the best solution would be to throw away that Ubuntu trash and use something else instead (like Linux Mint), but that's just me and Stallman lol^^

As for Windows, it handles very well the request for the system tray. My version works also fine, many people use it (me including).

**Comment by ViBENo1** [comment] 2016-03-21 04:44
nevermind. it just make no sense for me. but the tray icon why not just optional if it's one of the most common issues?

i mean the original version, not your fork. on Ubuntu the original just stop working after a few days. missing icons, missing profile pictures and never ending loading.

**Comment by Sytten** [comment] 2016-03-21 04:58
Well, I could make it optionnal, but since this app is fixed for replacement and I dont have a lot of time I didnt do it.

The original app didnt provide a system tray icon for linux and that annoyed me (thats why I forked it in the first place). The original should be working quite fine, what you describe should a lot like data corruption. Maybe try to delete all the files provided and settings (dont remember exactly where they are stored, but you should be able to find in the src) and reinstall. Did you messed with something related to GTK? because NW.JS use it.

**Comment by ViBENo1** [comment] 2016-03-21 16:33
i understand. i just don't get it why Linux version started to stuck at loading. i already cleared setting and all files. this started about three weeks ago. as far as i remember the biggest change in the meantime is the kernel updates and that's all. but that can't be related.

**Comment by Sytten** [comment] 2016-03-22 07:24
Linux version dont stuck at startup, yours maybe do but I use mine on Mint without any problem for almost 4 months...
Its an ubuntu related problem, that company add too much crap in their product...

**Comment by gnanet** [comment] 2016-04-09 23:57
On Ubuntu 12.04 the app.html wont load the messenger iframe : 
```
[7078:0410/015214:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
ATTENTION: option value of option force_s3tc_enable ignored.
[7078:0410/015216:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
ATTENTION: option value of option force_s3tc_enable ignored.
ATTENTION: option value of option force_s3tc_enable ignored.
[7078:0410/015216:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR

```

But the referenced URL https://www.messenger.com/login works inside Chrome 49.0.2623.112 (64-bit)

**Comment by gnanet** [comment] 2016-04-10 00:26
If the version of NW.js used with Facebook-Messenger-Desktop is not 0.13 then it should be upgraded. See:
https://github.com/nwjs/nw.js/issues/4017#issuecomment-201948373
https://github.com/popcorn-official/popcorn-desktop/issues/49

**Comment by gnanet** [comment] 2016-04-10 01:04
I can confirm building with nwjs 0.13.4 is the solution:


1. tried to start app
2. i copied the extracted contents (app.html app.js and so) on from /tmp/.com.google.Chrome..... into a folder
3. closed app
4. cd into the folder
5. started the app with /path/to/nw .
6. WORKS

**Comment by Sytten** [comment] 2016-04-13 04:25
As said on the PR:
I totally agree, I was waiting for the new version to be released and supported by NWBuilder, after my exams I will update my fork!

**Comment by Sytten** [comment] 2016-06-26 21:00
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/453 and https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Closed by Sytten** 2016-06-26 21:00 UTC
