### ISSUE TITLE
please disable the "Esc" = quit function

### ISSUE THREAD

**Issue by odessa2** [Aluxian/Facebook-Messenger-Desktop#208] opened 2015-08-04 18:52 UTC
When previewing a photo on facebook, pressing "Esc" will close the photo. In the Facebook-Messenger-Desktop app, at least in Linux, also closes the full app, which is really annoying..

**Comment by jackwilsdon** [comment] 2015-08-04 21:08
Looks like [Line 71 of app.js][https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/cdbf434e023ab877c6a2e6856eddd0b7853de3a2/src/app.js#L71] is the culprit. I'll submit a PR.

**Comment by odessa2** [comment] 2015-08-04 22:35
Thank you so much for the quick response and the commit..

**Comment by jackwilsdon** [comment] 2015-08-04 22:48
Not sure how long it will take to get it into an official build but I can build this commit for you if you want?

**Comment by orschiro** [comment] 2015-08-06 07:15
@jackwilsdon 

Thanks for addressing this very annoying issue! Would it be possible for you do build a 64-bit `deb` package for Ubuntu containing this fix?

Thankfully,

Robert

**Comment by jackwilsdon** [comment] 2015-08-06 17:47
I have uploaded a linux64 deb build [here][link]. I built it on Linux Mint, but it should work for any Debian-based OS.

  [link]: https://mega.nz/#!PJ82DRRY!0VkMe56Q7HJOlh2cyu25CBMBkgxCH_p9dzy_6RqLhaw

**Comment by orschiro** [comment] 2015-08-06 19:43
@jackwilsdon 

Thanks a lot! I managed to install it on eOS (Ubuntu 14.04) based. However, the escape still closes the window.

@odessa2 Can you confirm that it works?

**Comment by odessa2** [comment] 2015-08-06 20:01
@orschiro i am using arch and a modified pkgbuild from aur, i can confirm the esc key still closing the window.

**Comment by jackwilsdon** [comment] 2015-08-06 20:24
@orschiro @odessa2 Did you disable the ESC key by right clicking and turning off "Close with ESC key"?

**Comment by odessa2** [comment] 2015-08-06 20:28
@jackwilsdon works now, forgot that.. thanks!

**Comment by jackwilsdon** [comment] 2015-08-06 21:08
@odessa2 Great!

**Comment by orschiro** [comment] 2015-08-07 07:03
> Did you disable the ESC key by right clicking and turning off "Close with ESC key"?

This was the trick. Thank you so much for your time building the fixed version!

**Comment by jkugler** [comment] 2015-09-07 07:39
I can also confirm that this fix worked for me (Ubuntu 14.04).

**Comment by Sytten** [comment] 2016-06-28 03:17
The issue is resolved in the new beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Closed by Sytten** 2016-06-28 03:17 UTC
