### ISSUE TITLE
Integration with Ubuntu Unity

### ISSUE THREAD

**Issue by alexander-i-k** [Aluxian/Facebook-Messenger-Desktop#91] opened 2015-05-16 19:19 UTC
Hi, are you planning to better integrate with ubuntu unity? as for me, it would be cool

**Comment by jordanjay29** [comment] 2015-06-01 05:18
At the very least, a separate notification icon for the Unity bar would be a plus.

**Comment by Aluxian** [comment] 2015-06-13 08:15
Duplicate of https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/41

**Closed by Aluxian** 2015-06-13 08:15 UTC
