### ISSUE TITLE
Launcher is not the actual application

### ISSUE THREAD

**Issue by pedrofleck** [Aluxian/Facebook-Messenger-Desktop#234] opened 2015-08-30 23:17 UTC
I don't know how to title it, but when I open the application from the menu, it actually opens another that isn't the same, for example, the Messenger Desktop launcher with beautiful icon saved in Gnome Shell's sidebar above and the actual application opened with an ugly icon below:
![Sidebar](https://cloud.githubusercontent.com/assets/761321/9570010/43ba422c-4f53-11e5-90ad-46148222f072.png)
It shows in the Gnome Shell's upper bar as "unkwown" too:
![Unknown](https://cloud.githubusercontent.com/assets/761321/9570012/508d6ee8-4f53-11e5-96b3-6d293d8de0c6.png)
I'm using the last version from "[AUR](https://aur.archlinux.org/packages/messengerfordesktop/)" with Gnome 3.16 in ArchLinux.

**Comment by jackwilsdon** [comment] 2015-08-31 00:46
Not sure about the cause of the duplicate icons but take a look at #228 for information on the "Unknown" title.

**Comment by Hori873** [comment] 2015-11-13 14:01
Both are caused by the missing WM_CLASS property for the app's window

**Comment by Sytten** [comment] 2016-06-29 04:46
Should be fixed in the new beta, please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you still have that problem please open a new issue

**Closed by Sytten** 2016-06-29 04:46 UTC
