### ISSUE TITLE
App crashes on Linux when attempting to drag an image onto the window

### ISSUE THREAD

**Issue by zesterer** [Aluxian/Facebook-Messenger-Desktop#442] opened 2016-06-11 19:53 UTC
The title explains it all.

**Comment by Aluxian** [comment] 2016-06-11 19:55
Does it show a dialog? An error message anywhere? Let's debug this:

1. Open your terminal
2. Enter `export DEBUG=whatsie:*`
3. Enter `whatsie`

**Comment by Aluxian** [comment] 2016-06-11 19:56
_(ignore my previous (deleted) comment, I thought this was for Aluxian/Whatsie (again)...)_

**Comment by Sytten** [comment] 2016-06-13 01:04
Can you be more specific, I used this app for more than a year without encountering this problem...
I need a test case to reproduce it.
Can you also provide the distribution you are using...

**Comment by Sytten** [comment] 2016-06-26 02:16
Since we dont have more information I'm closing the issue

**Closed by Sytten** 2016-06-26 02:16 UTC
