### ISSUE TITLE
Tray icon for linux app would be great

### ISSUE THREAD

**Issue by longer83** [Aluxian/Facebook-Messenger-Desktop#296] opened 2015-11-30 12:48 UTC

**Comment by torokati44** [comment] 2015-11-30 13:27
+1

**Comment by avoidik** [comment] 2015-12-08 10:28
+1

**Comment by Sytten** [comment] 2015-12-15 03:50
Currently working on it, I will post something soon

**Comment by Sytten** [comment] 2015-12-15 22:56
Done you can grab it on my fork!

**Comment by pyrforos** [comment] 2015-12-16 21:32
forgive me im nood... how do  we install it?

**Comment by Sytten** [comment] 2015-12-17 05:48
I'm still resolving some bugs. I'm also working to integrate all the fix that other members made over the past months. I will build the installers probably tomorrow and provide the link here.

**Comment by pyrforos** [comment] 2015-12-17 07:13
Thank you! :)

**Comment by Sytten** [comment] 2015-12-18 14:56
Sorry I have to do some tasks that are taking me more time than what I thought, I won`t be able to finish correcting the bugs and package the app before sunday...

**Comment by Sytten** [comment] 2015-12-19 16:26
https://sytten.github.io/Facebook-Messenger-Desktop/

I duplicated the website and changed the download's links for linux only. This only issue that I found with the tray is with the theme selection, but its not a big deal. Enjoy!

**Comment by pyrforos** [comment] 2015-12-19 18:14
Thank you  but there is no tray  icon in  my system... I have kubuntu 15.10

**Comment by Sytten** [comment] 2015-12-19 18:40
well maybe you need an applet to display it.
I found that https://askubuntu.com/questions/598169/lost-system-tray-on-kubuntu

**Comment by pyrforos** [comment] 2015-12-20 09:27
did not even noticed it... http://blog.davidedmundson.co.uk/blog/xembed_back
Anyway thanks. It is still the best :)

**Comment by pyrforos** [comment] 2015-12-20 09:52
for anyone with the same problem  there is some kind of solution http://alien.slackbook.org/blog/support-for-old-school-xembed-system-tray-icons-in-plasma-5/

**Comment by Sytten** [comment] 2015-12-21 02:06
nice to hear you have found a solution :)

**Comment by longer83** [comment] 2015-12-22 14:41
Thanks for the tray icon, looks great, works perfect :)

**Comment by Sytten** [comment] 2015-12-23 08:44
No problem, I suggest you test my release. It has an auto update also so you will be notified next time I publish a release https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by cassiodoroVicinetti** [comment] 2015-12-30 13:54
@pyrforos In Kubuntu you need the `sni-qt` package. Anyway support for legacy tray icons will be back natively in [Plasma 5.5](https://www.kde.org/announcements/plasma-5.5.0.php).

**Comment by pyrforos** [comment] 2015-12-30 17:17
Thank you  @cassiodoroVicinetti .I have the sni-qt package installed and still no  tray icon.But it's ok im happy  as it is for now :)

**Comment by cassiodoroVicinetti** [comment] 2015-12-30 20:41
Instead on my system (Debian testing, Plasma 5.4.3, sni-qt 0.2.7+15.10.20150729-2) the icon appears.

The only problem is that it is not scaled to 22x22 (it's still 48x48):
![messengerfordesktop](https://cloud.githubusercontent.com/assets/1621526/12057079/b1083fc4-af3d-11e5-9929-d27a97737f06.png)

I've already tried to add a 22x22 icon into `/usr/share/icons/hicolors/22x22/apps/` but with no luck.

**Comment by Sytten** [comment] 2016-01-01 07:24
Not quite sure to understand the problem... As it is a specific problem to your distro I cant help very much...

**Comment by cassiodoroVicinetti** [comment] 2016-01-04 00:08
@pyrforos Sorry, you need the `libappindicator1` package (which is still a [legacy tray icon](http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/) in Plasma 5).

**Comment by billpcs** [comment] 2016-01-05 12:50
As a workaround you can edit the .desktop file and change **Exec** line to:

`Exec=env XDG_CURRENT_DESKTOP=Unity /opt/MessengerForDesktop/Messenger`

At least for me it is working.

**Comment by aia832003** [comment] 2016-01-10 23:24
I am seeing a tray icon in Unity Ubuntu 15.10, but it flickers on and off intermittently. Anyone else seeing this or have a solution?

**Comment by Sytten** [comment] 2016-01-11 00:23
Happens when you dont have access to the internet usually

**Comment by aia832003** [comment] 2016-01-11 00:25
I'm seeing this all the time with Unity. Goes from Messenger icon, to "picture frame" with red circle, to not showing at all.

**Comment by Sytten** [comment] 2016-01-11 00:29
You are not the only one: https://github.com/Sytten/Facebook-Messenger-Desktop/issues/14
Not quite sure what to do about it... Its probably an internal bug of NW.JS
Next week end I might have some time to update NW.JS to the latest beta version to test it

**Comment by aia832003** [comment] 2016-01-11 00:31
Thanks Sytten. Updates and notifications seem to work regardless. Look forward to continuing improvements and thanks for the great fork of this app.

**Comment by Sytten** [comment] 2016-01-11 03:00
Seems like they didn't update the builder used yet, so I'm stuck with version 0.12.3 of NWJS... I will chat a bit with the devs to see whats going on. I updated all the other dependencies. As soon as I have an answer I will build the app with the new version. Many bugs should be resolved with that update (I hope XD)...

**Comment by evgeni-tsn** [comment] 2016-01-19 13:05
Cannot open messenger from tray with double-click using Kubuntu 15.04 // Lastest build from @Sytten fork.

**Comment by cassiodoroVicinetti** [comment] 2016-01-19 13:08
@evgeni-tsn I can confirm this in Plasma 5, but I think it's not a big issue: you can right click and select "Show Messenger" in the context menu.

**Comment by pyrforos** [comment] 2016-05-28 18:30
so i'm  on plasma  5.5.5 .Still no  system stray  icon with the official version. With  the  test release i  have the tray icon  but  just like  the one of  cassiodoroVicinetti ... All the proposed packages installed... Its not really  a problem  but when i  have a new message, the icon doesn't change at all because its too  big to  be seen . Any  solution ?

**Comment by cassiodoroVicinetti** [comment] 2016-05-28 18:37
@pyrforos Try this workaround: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/296#issuecomment-168990541

**Comment by pyrforos** [comment] 2016-05-28 18:41
unbelievable!!! all this time wasn't working  because the path  was "/opt/MessengerForDesktop/Messenger" instead of "/opt/MessengerForDesktop" im so dump ...

**Comment by cassiodoroVicinetti** [comment] 2016-05-28 19:13
Mmm no, I think you did not understand the workaround. Are you using `XDG_CURRENT_DESKTOP=Unity`?

**Comment by pyrforos** [comment] 2016-05-28 19:46
yes yes i  did understand it . But now there is something strange going on... With  the parameter env XDG_CURRENT_DESKTOP=Unity  i have the icon but the cpu  usage is very high for some reason...  (plasmashell process is at 30%!!! ) without the parameter tray icon not ok but my  cpu usage is at normal levels (all these with  the test release .. with the official there is no tray icon)

**Comment by cassiodoroVicinetti** [comment] 2016-05-28 19:52
Try `env XDG_CURRENT_DESKTOP=GNOME`

**Comment by pyrforos** [comment] 2016-05-28 19:55
same...

**Comment by cassiodoroVicinetti** [comment] 2016-05-28 20:51
There are a lot of issues about the CPU usage:
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues?q=CPU
https://github.com/Sytten/Facebook-Messenger-Desktop/issues?q=CPU

It's not clear to me whether the CPU issue is related to the tray icon issue.

I'm using Debian with Plasma 5.4.3 and with `env XDG_CURRENT_DESKTOP=GNOME`. In my system the CPU usage of Messenger does not exceed 2.9%:
> `$ top -bn 60 -d 1  | grep 'Messenger' | gawk '{print $9}'  > top.txt`

output: [top.txt](https://github.com/Aluxian/Facebook-Messenger-Desktop/files/287995/top.txt) (I have 4 Messenger processes, so consider only lines 1-5-9-...)

@Sytten did not see any issue with the tray icon, even without `env XDG_CURRENT_DESKTOP`, during his tests on openSUSE with Plasma 5.5.4: https://github.com/Sytten/Facebook-Messenger-Desktop/pull/8#issuecomment-190259937

Anyway in the official Aluxian's version the tray icon was disabled in the code, while in the Sytten's version the tray icon was enabled back.

**Comment by pyrforos** [comment] 2016-05-29 10:44
now something  strange...
when i  run it  from kosnole i  get `messengerfordesktop 
[7796:0529/134103:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
pyrforos@fox3:~$ [7814:0529/134103:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1`
and the strange icon 
but  when i  run it as root i get  the correct icon.... and also  the same error ... 
Cpu problem without the env parameter doesn't exist..

**Comment by cassiodoroVicinetti** [comment] 2016-05-29 13:01
If it can help, when I run it from konsole I get:

> $ /opt/MessengerForDesktop/Messenger

```
[3262:0529/145656:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[3262:0529/145656:WARNING:app_indicator_icon.cc(274)] Could not encode icon
[3262:0529/145656:ERROR:browser_main_loop.cc(216)] GLib-GObject: /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:2517: signal 'child-added' is invalid for instance '0x56a9a5e0f0' of type 'GtkMenu'
[3262:0529/145656:ERROR:browser_main_loop.cc(216)] GLib-GObject: /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:2517: signal 'child-added' is invalid for instance '0x56a9a5e290' of type 'GtkMenu'
[3262:0529/145656:ERROR:browser_main_loop.cc(216)] GLib-GObject: /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:2517: signal 'child-added' is invalid for instance '0x56a9a5e430' of type 'GtkMenu'
```

> $ XDG_CURRENT_DESKTOP=GNOME /opt/MessengerForDesktop/Messenger

```
[3453:0529/145856:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.                                                                                                                                    
ATTENTION: default value of option force_s3tc_enable overridden by environment.
```

**Comment by Sytten** [comment] 2016-06-30 05:43
Resolved in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Closed by Sytten** 2016-06-30 05:43 UTC
Labels: 0 - New, bug, investigation
