### ISSUE TITLE
Escape key exits application entirely

### ISSUE THREAD

**Issue by chrylis** [Aluxian/Facebook-Messenger-Desktop#178] opened 2015-07-10 07:27 UTC
On Linux, pressing Esc closes the window and the entire application, as opposed to minimizing it to the taskbar or (as I understand is coming back soon) the tray.

**Comment by Majki** [comment] 2015-07-12 17:58
Confirming, Linux Mint 17 x64 here.

**Comment by bl4ckd0g** [comment] 2015-07-14 17:54
I can confirm this happens on Windows 8.1 as well.

**Comment by danwatco** [comment] 2015-07-15 18:33
Same issue here, Windows 8.1. 
ESC on a picture an application is closed.

**Comment by kevinwlau** [comment] 2015-07-26 06:53
In Windows 8.1, I noticed that pressing (and holding ESC) on a picture would close the picture. On release, the application window would close as well, but Messenger remained hidden in the system tray.

**Comment by devilirium** [comment] 2015-07-26 09:52
Aluxian is busy with porting to _Electron_. Once it's stable we'll fix these issues.

**Comment by mindworker** [comment] 2015-10-20 11:36
Any updates?

**Comment by jackwilsdon** [comment] 2015-10-21 01:39
I opened the pull request #209 a while ago, but nothing has happened since (not merged :disappointed:).

**Comment by Majki** [comment] 2015-10-21 18:43
Ping :)

**Comment by eallik** [comment] 2015-12-02 10:59
Also on Mac OS X — doesn't quit the app but hides the window; Cmd-Tab won't bring it back either; need to click on the Dock icon.

**Comment by Sytten** [comment] 2016-06-30 05:45
This is fixed in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Closed by Sytten** 2016-06-30 05:45 UTC
